import type { Metadata } from "next";
import { ConfigProvider } from "antd";
import { Inter } from "next/font/google";
import "./globals.scss";
import "animate.css";
import { designToken } from "@/helpers";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ConfigProvider
          theme={{
            token: {
              ...designToken,
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
